default:
  name: 'Verificación de BV Flora con Observation mediante base de datos'
  remote:
    processor: Observation\ObservationSpeciesProcessor
    options:
      datasource: obs_flora_database
  input:
    type: datasource
    name: bv_flora_csv_powo_ok # Datasource filename .yml
    parser: POWO\POWOSpeciesParser
  output_ok:
    type: csv
    path: ./data/output/BV_Flora-Observation_ok.csv
  output_errors:
    type: csv
    path: ./data/output/BV_Flora-Observation_error.csv

