default:
  name: 'Importación de especies que no están en Observation desde GBIF'
  remote:
    processor: Observation\ObservationSpeciesProcessor
  input:
    type: datasource
    name: bv_insect_database
    parser: Forum4Images\BV\FloraSpeciesParser
  output_ok:
    type: csv
    path: ./data/output/BV_Insectarium_ok.csv
  output_errors:
    type: pipeline
    path: BV_Insectarium_GBIF_import
