default:
  name: 'Verificación de BV con GBIF'
  remote:
    processor: GBIF\GBIFSpeciesProcessor
  input:
    type: datasource
    name: bv_insect_database # Datasource filename .yml
    parser: Forum4Images\BV\FloraSpeciesParser
  output_ok:
    type: csv
    path: ./data/output/BV_Odonata-GBIF_ok.csv
  output_errors:
    type: csv
    path: ./data/output/BV_Odonata-GBIF_error.csv

