default:
  name: 'Verificación de BV Invertebrados con Observation'
  remote:
    processor: Observation\ObservationSpeciesProcessor
  input:
    type: datasource
    name: bv_insect_database # Datasource filename .yml
    parser: Forum4Images\BV\FloraSpeciesParser
  output_ok:
    type: csv
    path: ./data/output/BV_Odonata-Obs_ok.csv
  output_errors:
    type: csv
    path: ./data/output/BV_Odonata-Obs_error.csv
