default: # Pipeline definition file, including input, outputs and the processor configuration
  name: 'Check BV coleoptera with Observation.org using a local database, and import them if missing' # Pipeline description
  remote: # Remote source processor configuration
    processor: Observation\ObservationSpeciesProcessor # Processor class, including namespace path under /Provider
    options: # Optional. Processor options, that will depend on every Processor class.
      datasource: obs_species_database # In this processor, this is the datasource used by the processor for species matching
      author_search: false # In this processor, use true to restrict species search by author
  input: # Input source configuration. This will be ignored if this pipeline is uses as output of other pipeline
    type: datasource # Input source type. It can be "csv", "datasource"
    name: bv_coleoptera_gbif_database # Datasource filename .yml
    parser: Forum4Images\BV\FloraSpeciesParser # Species name parser for this source
  output_ok: # Output for the correctly processed data
    type: csv # Output type. It can be "csv" or "pipeline"
    path: ./data/output/BV_Coleoptera-Observation_ok.csv # The path to the output file for CSV, or the name of the pipeline config file
  output_errors: # Output for the errors
    type: pipeline # Output type. It can be "csv" or "pipeline"
    path: GBIF_import # The path to the output file for CSV, or the name of the pipeline config file