default:
  name: 'Check Lepidoptera from BV database with GBIF, and then check it with Observation'
  remote:
    processor: GBIF\GBIFSpeciesProcessor
  input:
    type: datasource
    name: bv_lepidoptera_database # Datasource filename .yml
    parser: Forum4Images\BV\FloraSpeciesParser
  output_ok:
    type: pipeline
    path: BVLepidoptera-GBIF_Obs_DB
  output_errors:
    type: pipeline
    path: BVLepidoptera-NoGBIF_Obs_DB