default:
  name: 'Check Orthoptera from BV database with GBIF using GNVerifier'
  remote:
    processor: GNames\GNSpeciesProcessor
  input:
    type: datasource
    name: bv_orthoptera_database # Datasource filename .yml
    parser: Forum4Images\BV\FloraSpeciesParser
  output_ok:
    type: pipeline
    path: BVOrthoptera-GNGBIF_ObsDB
  output_errors:
    type: pipeline
    path: BVOrthoptera-NoGBIF_ObsDB