<?php

namespace Somms\BV2Observation\Provider\Forum4Images\BV;

use Somms\BV2Observation\Parser\GNSpeciesParser;
use Somms\BV2Observation\Provider\POWO\POWOSpeciesParser;

class FloraSpeciesParser extends GNSpeciesParser
{
    public function preprocessInput($input)
    {
        if(is_array($input)){
            $input = $input['cat_name'];
        }
        if(str_starts_with($input, 'CULT')){
            return false;
        }
        // Eliminamos las letras en mayúsculas del principio
        $input = preg_replace('/^[A-Z]+ /', '', $input);
        $input = preg_replace('/^[A-Z]+ /', '', $input);

        // Borramos palabras que no son forman parte del nombre
        $input = str_replace([
            'División ',
            'Phylum ',
            'Subphylum ',
            'Infraphylum ',
            'Clase ',
            'Subclase ',
            'Infraclase ',
            'Superorden ',
            'Orden ',
            'Suborden ',
            'Sección ',
            'Superfamilia ',
            'Familia ',
            'Fam. ',
            'Subfam. ',
            'Subfamilia ',
            'Tribu ',
            'Tribus ',
            'Trib. ',
            'Subtribu ',
            'Género ',
            'Genero ',
            'Gen. ',
            'Genus ',
            'Subgénero ',
            'Subgenero ',
            'Subgenus'
        ], '', $input);
        return parent::preprocessInput($input); // TODO: Change the autogenerated stub
    }

}