bv_coleoptera_gbif_database:
  type: 'database'
  dsn: 'pgsql:host=localhost;port=25432;dbname=waarneming'
  username: 'docker'
  password: 'docker'
  table_name: 'coleoptera_categories_filter'
  key_fieldname: 'gbif_species_name_author'