bv_flora_unmatched_db:
  type: 'database'
  dsn: 'pgsql:host=localhost;port=25432;dbname=waarneming'
  username: 'docker'
  password: 'docker'
  table_name: 'plantas_unmatched_categories'
  key_fieldname: 'cat_name'