obs_species_database:
  type: 'database'
  dsn: 'pgsql:host=localhost;port=25432;dbname=waarneming'
  username: 'docker'
  password: 'docker'
  table_name: 'obs_species'
  key_fieldname: 'name_scientific'
  author_fieldname: 'author'
  id_fieldname: 'id'